remote_host: "192.168.0.80"  # 共享文件夹所在主机的 IP 或主机名
share_name: "img"   # 共享文件夹名称
username: "administrator"
password: ""
remote_path: "01_秋名山_赛道/"      # 共享文件夹内的路径
local_path: "./local_folder"  # 本地文件夹路径